# Themes
include $HOME/.config/kitty/themes/colors.conf

# Shell
shell fish

# Fonts
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font
italic_font JetBrainsMono Nersd Font
bold_italic_font JetBrainsMono Nerd Font
font_size 11.0

# Cursors
cursor_shape beam
cursor_trail 1
cursor_blink_interval 0.5

# Windows
window_padding_width 20
background_opacity 0.98
confirm_os_window_close 0

# Auto-copy to clipboard
copy_on_select yes
