# SOURCES
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/generals.conf
source = ~/.config/hypr/hyprland/inputs.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/rules.conf

# MONITORS 
monitor=,preferred,auto,auto

# AUTOSTARTS
exec-once = $terminal
exec-once = awww-daemon
exec-once = hypridle

# ENVIRONMENT VARIABLES 
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24