source=~/.config/hypr/hyprlock/colors.conf

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 4, linear
    animation = inputFieldDots, 1, 2, linear
}

background { # Background Wallpaper
    monitor =
    path = $HOME/.config/hypr/hyprlock/Misono-Mika-b.jpg
    blur_passes = 3
    blur_size = 3
    brightness = 0.3
}

image { # Profile Pic
    monitor =
    path = $HOME/.config/hypr/hyprlock/Misono-Mika-p.png
    size = 120
    border_size = 0
    rounding = 100
    
    position = 0, 0
    valign = center
    halign = center

    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1
}

label { # Time label
    monitor =
    text = $TIME
    color = $foreground
    font_size = 11
    
    position = -70, 50
    valign = center
    halign = center
    zindex = 3
}

shape { # Background Time
    monitor =
    size = 80, 30
    color = $background
    rounding = 18

    position = -70, 50
    valign = center
    halign = center
    zindex = 2
      
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1
}

label { # Welcome label
    monitor =
    text = Welcome
    color = $foreground
    font_size = 11
    
    position = 70, -40
    valign = center
    halign = center
    zindex = 3
}

shape { # Background Welcome
    monitor =
    size = 80, 30
    color = $background
    rounding = 18

    position = 70, -40
    valign = center
    halign = center
    zindex = 2
      
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1
}

label { # User label
    monitor =
    text =    $USER
    color = $foreground
    font_size = 11
    
    position = -150, 28
    halign = center
    valign = bottom
}

shape { # Background User
    monitor =
    size = 80, 35
    color = $background
    rounding = 18

    position = -150, 20
    halign = center
    valign = bottom
      
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1
}

label { # Layout
    monitor =
    text = $LAYOUT
    font_size = 10
    color = $foreground
    
    position = 170, 29
    halign = center
    valign = bottom
}

shape { # Background Layout
    monitor =
    size = 120, 35
    color = $background
    rounding = 18
    
    position = 170, 20
    halign = center
    valign = bottom
      
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1
}

input-field { # input
    monitor =
    size = 200, 35
    rounding = 18
    outline_thickness = 0
    font_color = $foreground
    inner_color = $background
    check_color = rgba(0, 0, 0, 0.2)
    fail_color = rgb(249, 53, 102)
    fail_text = $PAMFAIL
    fade_on_empty = false
    placeholder_text = Enter Password
    dots_center = true
    dots_size = 0.35
    dots_spacing = 0.4
    
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $shadow
    shadow_boost = 1

    position = 0, 20
    halign = center
    valign = bottom
}