# SOURCE
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/generals.conf
source = ~/.config/hypr/hyprland/inputs.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/rules.conf

# MONITORS 
monitor=,preferred,auto,auto

# AUTOSTART 
exec-once = awww-daemon
exec-once = $terminal
exec-once = hypridle
exec-once = qs
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# ENVIRONMENT VARIABLES 
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
