$shadow = rgb(0, 0, 0)
$font_color  = rgb(255, 255, 255)
$inner_color  = rgb(19, 19, 19)
$check_color = rgba(0, 0, 0, 0)
$fail_color = rgb(249, 53, 102)

general {
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/Wallpapers/background.jpg
}

label {
    monitor =
    text = $TIME
    font_size = 40
    valign = center
    halign = center
    position = 0, 80
}

label {
    monitor =
    text = Welcome back $USER
    font_size = 20
    valign = center
    halign = center
    position = 0, 30
}

label {
    monitor =
    text = $LAYOUT
    font_size = 12
    valign = bottom
    halign = right
    position = -40, 20
}

input-field {
    monitor =
    size = 18%, 6%
    outline_thickness = 0
    rounding = 15
    font_color = $font_color
    inner_color = $inner_color
    check_color = $check_color
    fail_color = $fail_color
    fail_text = $PAMFAIL
    fade_on_empty = false
    placeholder_text = password...
    dots_center = true
    dots_size = 0.3
    dots_spacing = 0.4
    shadow_passes = 1
    shadow_size = 4
    shadow_color = $shadow
    shadow_boost = 1
    position = 0, -20
    halign = center
    valign = center
}