# CURSOR
cursor                #a3c9fe
cursor_text_color     #00315b

# BACKGROUNDS
background            #181821
foreground            #e1e2e8
selection_foreground  #f4d9ff
selection_background  #bbc7db
url_color             #bbc7db

# BLACK
color0                #111418
color8                #32353a

# RED
color1                #ffb4ab
color9                #a3c9fe

# GREEN
color2                #a3c9fe
color10               #d7e3f8

# YELLOW
color3                #bbc7db
color11               #d8bde3

# BLUE
color4                #1e4875
color12               #e1e2e8

# MAGENTA
color5                #3c4758
color13               #bbc7db

# CYAN
color6                #a3c9fe
color14               #d8bde3

# WHITE
color7                #e1e2e8
color15               #e1e2e8