# CURSORS
cursor            #a6c8ff
cursor_text_color #02315f

# BACKGROUNDS
background            #0a0a0a
foreground            #e1e2e9
selection_foreground  #f7d8ff
selection_background  #bdc7dc
url_color             #bdc7dc

# BLACK
color0  #111318
color8  #32353a

# RED
color1   #ffb4ab
color9   #a6c8ff

# GREEN
color2  #a6c8ff
color10 #d9e3f8

# YELLOW
color3  #bdc7dc
color11 #dabde2

# BLUE
color4  #234776
color12 #e1e2e9

# MAGENTA
color5  #3d4758
color13 #bdc7dc

# CYAN
color6   #a6c8ff
color14 #dabde2

# WHITE
color7  #e1e2e9
color15 #e1e2e9