# ANIMATIONS
layerrule = animation slide bottom, match:namespace rofi
layerrule = animation slide right, match:namespace notifications
windowrule = animation slide bottom, match:class waypaper
windowrule = animation slide bottom, match:class kitty
windowrule = animation slide bottom, match:class brave-browser
layerrule = animation slide right, match:namespace logout_dialog

# BLURS
layerrule = blur true, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi

# FLOATS
windowrule = float on, match:class waypaper
