# ANIMATIONS
layerrule = animation slide, match:namespace rofi
layerrule = animation slide, match:namespace notifications
windowrule = animation slide, match:class waypaper
windowrule = animation slide, match:class kitty
windowrule = animation slide, match:class brave-browser

# BLURS
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi

# FLOATS
windowrule = float on, match:class waypaper
