# CURSOR
cursor                {{ colors.primary.dark.hex }}
cursor_text_color     {{ colors.on_primary.dark.hex }}

# BACKGROUNDS
background            #1d1d1e
foreground            {{colors.on_surface.default.hex}}
selection_foreground  {{ colors.on_tertiary_container.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}
url_color             {{ colors.secondary.dark.hex }}

# BLACK
color0                {{ colors.surface.dark.hex }}
color8                {{ colors.surface_container_highest.dark.hex }}

# RED
color1                {{colors.error.default.hex}}
color9                {{ colors.primary.dark.hex }}

# GREEN
color2                {{colors.primary.default.hex}}
color10               {{ colors.secondary_fixed.dark.hex }}

# YELLOW
color3                {{ colors.secondary.dark.hex }}
color11               {{ colors.tertiary.dark.hex}}

# BLUE
color4                {{ colors.on_primary_fixed_variant.dark.hex }}
color12               {{ colors.on_surface.dark.hex }}

# MAGENTA
color5                {{ colors.on_secondary_fixed_variant.dark.hex }}
color13               {{ colors.secondary.dark.hex }}

# CYAN
color6                {{colors.primary.dark.hex}}
color14               {{ colors.tertiary.dark.hex }}

# WHITE
color7                {{colors.on_surface.default.hex}}
color15               {{colors.on_surface.default.hex}}
